### ISSUE TITLE
Error on pip install

### ISSUE THREAD

**Issue by sofroniewn** [manzt/napari-lazy-openslide#3]
Just got this error on attempting install

```python-traceback
czirwc1macos2701:napari nsofroniew$ pip install napari-lazy-openslide
Collecting napari-lazy-openslide
  Downloading napari_lazy_openslide-0.0.1-py3-none-any.whl (7.1 kB)
Requirement already satisfied: zarr>=0.2.4 in /Users/nsofroniew/opt/anaconda3/lib/python3.7/site-packages (from napari-lazy-openslide) (2.3.2)
Collecting setuptools==45
  Downloading setuptools-45.0.0-py2.py3-none-any.whl (583 kB)
     |████████████████████████████████| 583 kB 2.8 MB/s
Requirement already satisfied: numpy>=0.1.19 in /Users/nsofroniew/opt/anaconda3/lib/python3.7/site-packages (from napari-lazy-openslide) (1.18.1)
Collecting dask[array]>=2.20.0
  Using cached dask-2.20.0-py3-none-any.whl (826 kB)
Collecting openslide-python>=1.1.1
  Downloading openslide-python-1.1.1.tar.gz (312 kB)
     |████████████████████████████████| 312 kB 12.9 MB/s
    ERROR: Command errored out with exit status 1:
     command: /Users/nsofroniew/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/30/g_dcv_xs2l315nvmwq0_v52r0000gr/T/pip-install-_l4_fq5z/openslide-python/setup.py'"'"'; __file__='"'"'/private/var/folders/30/g_dcv_xs2l315nvmwq0_v52r0000gr/T/pip-install-_l4_fq5z/openslide-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/30/g_dcv_xs2l315nvmwq0_v52r0000gr/T/pip-install-_l4_fq5z/openslide-python/pip-egg-info
         cwd: /private/var/folders/30/g_dcv_xs2l315nvmwq0_v52r0000gr/T/pip-install-_l4_fq5z/openslide-python/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/30/g_dcv_xs2l315nvmwq0_v52r0000gr/T/pip-install-_l4_fq5z/openslide-python/setup.py", line 2, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/Users/nsofroniew/opt/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by sofroniewn** [comment]
Looks like an `openslide-python` install error

**Comment by sofroniewn** [comment]
see comment here https://github.com/openslide/openslide-python/issues/80#issuecomment-646985909 and project here https://pypi.org/project/openslide-wrapper/1.1.2/

**Comment by sofroniewn** [comment]
changing dependence to `openslide-wrapper==1.1.2` could solve it

**Comment by sofroniewn** [comment]
I cloned the repo, changed that dependency, and then did `pip install -e .` but don't see the plugin in the napari installed plugins menu within napari. I do see the following after `pip freeze` though
```
-e git+https://github.com/manzt/napari-lazy-openslide@7556e1f90c5ee2c18862c75060fdfdec3a70d9f0#egg=napari_lazy_openslide
```

Thoughts @tlambert03? I might need to try a clean environment ....

**Comment by manzt** [comment]
I changed to `openslide-wrapper==1.1.2` in #2, and now don't run into `setuptools` issue on ubuntu (thanks for the suggestion). Still need to figure out how to install `openslide` in the windows and mac envs. I can't speak to the discoverability with napari, but I just created new environment and was able to install via `pip install -e .`.

**Comment by Czaki** [comment]
openside problem could be solved with creating wheels for `openslide-wrapper` or `openslide-python`. Then wheel will contain also library. For macos and linux it will could be easy beacuse `delocate` and `auditwheel` could collect all needed files. This could be easy automated with `cibuildwheel`.  I could help with this part (I use this project in my projecta and I'm active contributor) https://github.com/joerick/cibuildwheel/

**Comment by sofroniewn** [comment]
Yup, I needed to install `openslide` first - my bad. `brew install openslide` worked for me. For now maybe just add a `Step 1. Install OpenSlide` and then this link the the readme on this repo https://openslide.org/download/. Apologies if i missed it and it's already there.

Works amazing now!!!

**Comment by manzt** [comment]
> Apologies if i missed it and it's already there.

Nope, not already there! Adding to the README. 

@Czaki I really don't know what this would entail, but making it easier to install would be a great contribution. I don't have much experience with python packaging, so PRs are certainly welcome!

**Comment by Czaki** [comment]
> @Czaki I really don't know what this would entail, but making it easier to install would be a great contribution. I don't have much experience with python packaging, so PRs are certainly welcome!

This should be PR to `openslide-python`. I could prepare fix. But I'm not familiar with `openslide` and not sure how to convince its maintainer to use it.

**Comment by Czaki** [comment]
@manzt It will take longer time. There is need to setup and build from source multiple libraries:

> This library requires zlib, libpng, libjpeg, libtiff, OpenJPEG 1.x or >= 2.1,
GDK-PixBuf, libxml2, SQLite >= 3.6.20, cairo >= 1.2, and glib >= 2.16.
Leica and Ventana support require libtiff >= 4.

**Comment by sdvillal** [comment]
Since now openslide-python 1.1.2 is in pypi, I think we can revert depending on wrapper and close this issue

As a side note, there are conda-forge friendly and up-to-date, multiplatform conda packages for openslide and openslide-python: ```conda install -c sdvillal openslide-python```. I will try to contribute these to conda-forge when time allows.
